on: [push]
name: Create an issue on push
jobs:
  stuff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: JasonEtco/create-an-issue@v2.4.0
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/failed_schedule_issue_template.md

